# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
config.vm.box = "bento/centos-8.4"
config.vm.define "server" do |server|
server.vm.hostname = "server.loc"
server.vm.network "private_network", ip: "192.168.56.10"
end
config.vm.define "client" do |client|
client.vm.hostname = "client.loc"
client.vm.network "private_network", ip: "192.168.56.20"
end
config.vm.define "client2" do |client2|
client2.vm.hostname = "server.loc"
client2.vm.network "private_network", ip: "192.168.56.30"
end
config.vm.define "client3" do |client3|
client3.vm.hostname = "client.loc"
client3.vm.network "private_network", ip: "192.168.56.40"
end
end
