Vagrant.configure("2") do |config|
    # Указываем ОС, версию, количество ядер и ОЗУ
  config.vm.box = "bento/centos-8.4"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.limit = "all"
    ansible.become = "true"
  end
 
  #  config.vm.provider :virtualbox do |v|
  #    v.memory = 768
  #    v.cpus = 1
  #  end
  
    # Указываем имена хостов и их IP-адреса
    boxes = [
      { :name => "ipa.otus.lan",
        :ip => "192.168.57.10",
      },
      { :name => "client1.otus.lan",
        :ip => "192.168.57.11",
      },
      { :name => "client2.otus.lan",
        :ip => "192.168.57.12",
      }
    ]
    # Цикл запуска виртуальных машин
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.network "private_network", ip: opts[:ip]
      end
    end
  end

